name: Vistits CI/CD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.dev
          tags: iuriinedostup/docker-react
          outputs: type=docker,dest=/tmp/docker-react.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-react
          path: /tmp/docker-react.tar
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-react
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/docker-react.tar

      - name: test app
        run: docker run -e CI=true iuriinedostup/docker-react npm run test
